name: Interlogica Frontend CI

on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]

jobs:
  build:
    name: Build react build folder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      # - name: Unit tests
      #  run: npm test -- --ci

      - name: Build frontend
        run: CI=false npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: build/

  docker:
    name: Push Docker Image
    runs-on: ubuntu-latest
    needs: build
    permissions:
      packages: write
    env:
      DOCKER_TAG_GHCR: ghcr.io/${{ github.repository_owner }}/interlogica_front_end:${{ github.sha }}
    steps:
      - uses: actions/checkout@v5

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: build/

      - name: GHCR login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Build docker tag
        run: |
          echo "Packing application to registry..."
          docker build -t ${{ env.DOCKER_TAG_GHCR }} .

      - name: Push docker tag to ghcr
        run: |
          echo "Pushing to github..."
          docker push ${{ env.DOCKER_TAG_GHCR }}
