name: Interlogica CI

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

  docker:
    name: Push Docker Image
    runs-on: ubuntu-latest
    needs: build
    permissions:
      packages: write
    env:
      DOCKER_TAG_GHCR: ghcr.io/${{ github.repository_owner }}/interlogica:${{ github.sha }}
    steps:
      - uses: actions/checkout@v5

      - name: Build docker tag
        run: |
          echo "Packing application to registry..."
          docker buildx build -t ${{ env.DOCKER_TAG }} -t ${{ env.DOCKER_TAG_GHCR }} .

      - name: GHCR login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username giusetega --password-stdin

      - name: Push docker tag to docker hub and ghcr
        run: |
          echo "Pushing to github..."
          docker push ${{ env.DOCKER_TAG_GHCR }}
